name: softeng_for_sci
channels:
  - conda-forge
  - defaults
dependencies:
  - black=23.10.1
  - cookiecutter=2.4.0
  - debugpy=1.8.0
  - ipython=8.17.2
  - jupyter=1.0.0
  - numpy=1.26.0
  - pandas=2.1.2
  - python=3.11
  - ruff=0.1.3
  - scikit-learn=1.3.2
  - scipy=1.11.3
  - click
  - pytest
  - sphinx
  - myst-parser
