name: seminar_project
channels:
  - conda-forge
dependencies:
  - cookiecutter
  - ipython=9.9.0
  - jupyter=1.1
  - numpy=2.4
  - pandas=2.3
  - python=3.14
  - ruff
  - scikit-learn=1.8
  - scipy=1.17
  - click=8.3
  - pytest
  - sphinx
  - myst-parser
  - nbsphinx
